# Generated by Django 4.2a1 on 2023-02-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="task",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ اتمام"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
        ),
    ]
