### Variables
@base = http://localhost:9000/v1
@auth-token = 480a617af0dd6665bb546e92f3c439fa27ac0eb7
@task_id = f57ac031-ce9c-439b-8193-2f9f2c8a5ec4
@contentType = application/json
###
# Register new user
POST {{base}}/auth/users/
Content-Type: {{contentType}}

{    
    "username":"",
    "password": ""
}

###
# Get auth token
POST {{base}}/auth/token/login/
Content-Type: {{contentType}}

{    
    "username":"druid",
    "password": "hijack1001"
}

###
# Create new task
POST {{base}}/tasks/
Authorization: Token {{auth-token}}
Content-Type: {{contentType}}

{
    "title": "docker test",
    "description": "i have to"
}

###
# Get all tasks that the user own
GET {{base}}/tasks/recent/
Authorization: Token {{auth-token}}
Content-Type: {{contentType}}
###
# Get detail of a task that user owns
GET {{base}}/tasks/{{task_id}}/
Authorization: Token {{auth-token}}
Content-Type: {{contentType}}
###
# Update a task 
PATCH {{base}}/tasks/{{task_id}}/
Authorization: Token {{auth-token}}
Content-Type: {{contentType}}

{
    "title": "no no"
}

###
# Delete a task
DELETE {{base}}/tasks/{{task_id}}/
Authorization: Token {{auth-token}}
Content-Type: {{contentType}}
###