version: '3.9'
services:
  django-api:
    build: .
    volumes:
      - .:/code
      - static-data:/code/web/static
      - media-data:/code/web/media
    ports:
      - "9000:9000"
    command: sh -c "python /code/manage.py wait_for_db && python /code/manage.py runserver 0.0.0.0:9000"
    depends_on:
      - postgres
    env_file:
      - env/django.env

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - env/postgres.env
    ports:
      - "5431:5432"

volumes:
  postgres-data:
  static-data:
  media-data:
