version: '3.9'
services:
  django-api:
    build: .
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    command: sh -c "python /code/manage.py wait_for_db && python /code/manage.py runserver 0.0.0.0:9000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=task_api
      - POSTGRES_USER=druid
      - POSTGRES_PASSWORD=asmari1001
    ports:
      - "5431:5432"

volumes:
  postgres-data:
