version: '3.9'
services:

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - env/postgres.env
    ports:
      - 5431:5432
  redis:
    image: redis:7.2-alpine
    ports:
      - 6378:6379

volumes:
  postgres-data: