# Generated by Django 5.0b1 on 2023-11-02 16:54

import api.accounts.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", api.accounts.models.UserManger()),
            ],
        ),
    ]
