# Generated by Django 5.0b1 on 2023-10-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="tasks.tag"),
        ),
    ]
