# Generated by Django 5.0b1 on 2023-11-02 16:54

import api.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_task_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.tasks.models.attachment_file_name,
                verbose_name="مستندات",
            ),
        ),
    ]
