# Generated by Django 5.0b1 on 2023-11-02 16:54

from django.core.files.storage import FileSystemStorage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_task_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=FileSystemStorage(),
                upload_to="uploads",
                verbose_name="مستندات",
            ),
        ),
    ]
